
#http://localhost:8080/laskomed

server:
  port: 8080
  servlet:
    context-path: /laskomed/api

# api store dla zewnętrznego api
api:
  petStore:
    url: https://petstore3.swagger.io/api/v3/

spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    show-sql: true
    url: jdbc:postgresql://localhost:5432/laskomed
    username: postgres
    password: 1234
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  # tylko na developmencie
logging:
  level:
    org:
      springframework:
        security: INFO