
server:
  port: 8080
  servlet:
    context-path: /laskomed/api
app:
  jwt-secret: FxfGyCNl3uUwR2b/Te+s+TOe2l2FjL8ceWjA32vG62n0kY1/A+yW7M3fZdV6wLy9
  jwt-expiration-milliseconds: 86400000

spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    show-sql: true
    url: jdbc:postgresql://postgres:5432/laskomed  # pod dockera
#    url: jdbc:postgresql://localhost:5432/laskomed  # pod localne uruchomienie aplikacji
    username: postgres
    password: 1234
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
